In [ ]:
import numpy as np
import pandas as pd
import pyarrow as pa
import lightgbm as lgb
import xgboost as xgb
from scipy.stats import poisson, spearmanr
from sklearn.calibration import CalibratedClassifierCV
from pandas.api.types import CategoricalDtype
from sklearn.metrics import log_loss, accuracy_score
from typing import List, Tuple, Dict, Generator
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import log_loss, accuracy_score
import warnings
from pathlib import Path
import json
import gc
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", None)


TRAIN_MODE = True
COMP_TYPE = f"{COMP_TYPE}"
DATA_PATH = f"../../../data/{COMP_TYPE}/"
DIR_PATH_SUBSET = f"../../../outputs/{COMP_TYPE}/feature_selection_subset/"
DIR_PATH_METRIC_RESULT = f"../../../outputs/{COMP_TYPE}/model_metrics/"
DIR_PATH_PICKLE_FILE = f"../../../outputs/{COMP_TYPE}/models/"

gc.collect()
df = pd.read_parquet(DATA_PATH + "club_features_full.parquet")
df.head()

,match_id,match_datetime_utc,season_id,home_team_id,away_team_id,home_score,away_score,home_venue_id,home_referee_id,home_macro_rolling_goals,home_macro_rolling_fouls,home_macro_rolling_yellows,home_team_avg_goals_last_5,home_team_avg_xg_last_5,home_team_avg_buildup_last_5,home_team_avg_conceded_last_5,home_team_clean_sheet_pct_last_5,home_team_avg_xga_last_5,home_team_avg_ppda_last_5,home_team_avg_yellows_last_5,home_opponent_avg_yellows_last_5,home_team_avg_reds_last_5,home_opponent_avg_reds_last_5,home_team_avg_cards_per_foul_last_5,home_team_avg_fouls_committed_last_5,home_team_avg_fouls_drawn_last_5,home_team_avg_fouls_padj_last_5,home_team_avg_tackles_last_5,home_team_avg_tackle_fail_rate_last_5,home_opponent_avg_tackles_last_5,home_opponent_avg_tackles_succ_last_5,home_opponent_avg_tackle_succ_rate_last_5,home_team_avg_possession_last_5,home_opponent_avg_dribbles_last_5,home_team_avg_dribbles_last_5,home_team_avg_duels_last_5,home_team_avg_aerial_duels_last_5,home_team_avg_aerial_win_rate_last_5,home_team_avg_fouled_final_third_last_5,home_team_avg_foul_opp_final_third_last_5,home_team_avg_dispossessed_last_5,home_opponent_avg_dispossessed_last_5,home_team_avg_clearances_last_5,home_team_avg_recoveries_last_5,home_opponent_avg_touches_in_box_last_5,home_team_avg_touches_in_box_last_5,home_team_avg_sot_last_5,home_opponent_avg_sot_last_5,home_team_avg_shots_last_5,home_team_avg_shots_faced_last_5,home_team_avg_corners_last_5,home_team_avg_corners_against_last_5,home_opponent_avg_crosses_last_5,home_team_avg_crosses_last_5,home_team_avg_free_kicks_last_5,home_team_avg_offsides_last_5,home_opponent_avg_offsides_last_5,home_team_avg_goal_kicks_last_5,home_opponent_avg_goal_kicks_last_5,home_team_avg_goals_last_10,home_team_avg_xg_last_10,home_team_avg_buildup_last_10,home_team_avg_conceded_last_10,home_team_clean_sheet_pct_last_10,home_team_avg_xga_last_10,home_team_avg_ppda_last_10,home_team_avg_yellows_last_10,home_opponent_avg_yellows_last_10,home_team_avg_reds_last_10,home_opponent_avg_reds_last_10,home_team_avg_cards_per_foul_last_10,home_team_avg_fouls_committed_last_10,home_team_avg_fouls_drawn_last_10,home_team_avg_fouls_padj_last_10,home_team_avg_tackles_last_10,home_team_avg_tackle_fail_rate_last_10,home_opponent_avg_tackles_last_10,home_opponent_avg_tackles_succ_last_10,home_opponent_avg_tackle_succ_rate_last_10,home_team_avg_possession_last_10,home_opponent_avg_dribbles_last_10,home_team_avg_dribbles_last_10,home_team_avg_duels_last_10,home_team_avg_aerial_duels_last_10,home_team_avg_aerial_win_rate_last_10,home_team_avg_fouled_final_third_last_10,home_team_avg_foul_opp_final_third_last_10,home_team_avg_dispossessed_last_10,home_opponent_avg_dispossessed_last_10,home_team_avg_clearances_last_10,home_team_avg_recoveries_last_10,home_opponent_avg_touches_in_box_last_10,home_team_avg_touches_in_box_last_10,home_team_avg_sot_last_10,home_opponent_avg_sot_last_10,home_team_avg_shots_last_10,home_team_avg_shots_faced_last_10,home_team_avg_corners_last_10,home_team_avg_corners_against_last_10,home_opponent_avg_crosses_last_10,home_team_avg_crosses_last_10,home_team_avg_free_kicks_last_10,home_team_avg_offsides_last_10,home_opponent_avg_offsides_last_10,home_team_avg_goal_kicks_last_10,home_opponent_avg_goal_kicks_last_10,home_team_avg_goals_last_20,home_team_avg_xg_last_20,home_team_avg_buildup_last_20,home_team_avg_conceded_last_20,home_team_clean_sheet_pct_last_20,home_team_avg_xga_last_20,home_team_avg_ppda_last_20,home_team_avg_yellows_last_20,home_opponent_avg_yellows_last_20,home_team_avg_reds_last_20,home_opponent_avg_reds_last_20,home_team_avg_cards_per_foul_last_20,home_team_avg_fouls_committed_last_20,home_team_avg_fouls_drawn_last_20,home_team_avg_fouls_padj_last_20,home_team_avg_tackles_last_20,home_team_avg_tackle_fail_rate_last_20,home_opponent_avg_tackles_last_20,home_opponent_avg_tackles_succ_last_20,home_opponent_avg_tackle_succ_rate_last_20,home_team_avg_possession_last_20,home_opponent_avg_dribbles_last_20,home_team_avg_dribbles_last_20,home_team_avg_duels_last_20,home_team_avg_aerial_duels_last_20,home_team_avg_aerial_win_rate_last_20,home_team_avg_fouled_final_third_last_20,home_team_avg_foul_opp_final_third_last_20,home_team_avg_dispossessed_last_20,home_opponent_avg_dispossessed_last_20,home_team_avg_clearances_last_20,home_team_avg_recoveries_last_20,home_opponent_avg_touches_in_box_last_20,home_team_avg_touches_in_box_last_20,home_team_avg_sot_last_20,home_opponent_avg_sot_last_20,home_team_avg_shots_last_20,home_team_avg_shots_faced_last_20,home_team_avg_corners_last_20,home_team_avg_corners_against_last_20,home_opponent_avg_crosses_last_20,home_team_avg_crosses_last_20,home_team_avg_free_kicks_last_20,home_team_avg_offsides_last_20,home_opponent_avg_offsides_last_20,home_team_avg_goal_kicks_last_20,home_opponent_avg_goal_kicks_last_20,home_xi_avg_last_5_goals,home_xi_avg_last_5_xg,home_xi_avg_last_5_shots_taken,home_xi_avg_last_20_goals,home_xi_avg_last_20_xg,home_xi_avg_season_yellow_cards_per_90,home_xi_avg_season_red_cards_per_90,home_xi_avg_season_fouls_committed_per_90,home_xi_avg_season_goals_per_game,home_xi_avg_season_xg_per_game,home_xi_avg_finishing_overperformance_per_90,home_xi_avg_recent_match_fitness,home_starters_count,home_roll_5_line_xg_ATT,home_roll_5_line_xg_BENCH,home_roll_5_line_xg_DEF,home_roll_5_line_xg_MID,home_roll_5_line_goals_ATT,home_roll_5_line_goals_BENCH,home_roll_5_line_goals_DEF,home_roll_5_line_goals_MID,home_roll_5_line_sot_ATT,home_roll_5_line_sot_BENCH,home_roll_5_line_sot_DEF,home_roll_5_line_sot_MID,home_roll_5_line_tackles_ATT,home_roll_5_line_tackles_BENCH,home_roll_5_line_tackles_DEF,home_roll_5_line_tackles_MID,home_roll_5_line_fouls_ATT,home_roll_5_line_fouls_BENCH,home_roll_5_line_fouls_DEF,home_roll_5_line_fouls_MID,home_roll_5_line_market_val_ATT,home_roll_5_line_market_val_BENCH,home_roll_5_line_market_val_DEF,home_roll_5_line_market_val_MID,home_roll_5_team_match_shot_hhi,home_roll_5_team_match_top_shooter_shots,home_roll_5_team_squad_value_eur,home_team_last_20_goal_dependency_top2,home_schedule_days_rest,home_schedule_next_game_is_high_priority,home_schedule_next_game_is_diff_tournament,home_schedule_avg_opp_elo_vs_league_last_5,home_schedule_next_opp_elo_vs_league,home_schedule_is_trap_game,home_season_ppg,home_season_gd_per_game,home_global_form_points_last_5,home_pct_goals_last_5_goals_Mid_Left,home_pct_goals_last_5_goals_Close_Center,home_pct_goals_last_5_goals_Mid_Center,home_pct_goals_last_5_goals_Deep_Center,home_pct_goals_last_5_goals_Close_Left,home_pct_goals_last_5_goals_Mid_Right,home_pct_goals_last_5_goals_Deep_Right,home_pct_goals_last_5_goals_Deep_Left,home_pct_goals_last_5_goals_Close_Right,home_pct_sot_last_5_sot_Mid_Left,home_pct_sot_last_5_sot_Close_Center,home_pct_sot_last_5_sot_Mid_Center,home_pct_sot_last_5_sot_Deep_Center,home_pct_sot_last_5_sot_Close_Left,home_pct_sot_last_5_sot_Mid_Right,home_pct_sot_last_5_sot_Deep_Right,home_pct_sot_last_5_sot_Deep_Left,home_pct_sot_last_5_sot_Close_Right,home_pct_blocks_last_5_blocks_Mid_Left,home_pct_blocks_last_5_blocks_Close_Center,home_pct_blocks_last_5_blocks_Mid_Center,home_pct_blocks_last_5_blocks_Deep_Center,home_pct_blocks_last_5_blocks_Close_Left,home_pct_blocks_last_5_blocks_Mid_Right,home_pct_blocks_last_5_blocks_Deep_Right,home_pct_blocks_last_5_blocks_Deep_Left,home_pct_blocks_last_5_blocks_Close_Right,home_pct_goals_last_5_goals_Header,home_pct_goals_last_5_goals_Foot,home_pct_sot_last_5_sot_Header,home_pct_sot_last_5_sot_Foot,home_pct_blocks_last_5_blocks_Header,home_pct_blocks_last_5_blocks_Foot,home_pct_goals_last_10_goals_Mid_Left,home_pct_goals_last_10_goals_Close_Center,home_pct_goals_last_10_goals_Mid_Center,home_pct_goals_last_10_goals_Deep_Center,home_pct_goals_last_10_goals_Close_Left,home_pct_goals_last_10_goals_Mid_Right,home_pct_goals_last_10_goals_Deep_Right,home_pct_goals_last_10_goals_Deep_Left,home_pct_goals_last_10_goals_Close_Right,home_pct_sot_last_10_sot_Mid_Left,home_pct_sot_last_10_sot_Close_Center,home_pct_sot_last_10_sot_Mid_Center,home_pct_sot_last_10_sot_Deep_Center,home_pct_sot_last_10_sot_Close_Left,home_pct_sot_last_10_sot_Mid_Right,home_pct_sot_last_10_sot_Deep_Right,home_pct_sot_last_10_sot_Deep_Left,home_pct_sot_last_10_sot_Close_Right,home_pct_blocks_last_10_blocks_Mid_Left,home_pct_blocks_last_10_blocks_Close_Center,home_pct_blocks_last_10_blocks_Mid_Center,home_pct_blocks_last_10_blocks_Deep_Center,home_pct_blocks_last_10_blocks_Close_Left,home_pct_blocks_last_10_blocks_Mid_Right,home_pct_blocks_last_10_blocks_Deep_Right,home_pct_blocks_last_10_blocks_Deep_Left,home_pct_blocks_last_10_blocks_Close_Right,home_pct_goals_last_10_goals_Header,home_pct_goals_last_10_goals_Foot,home_pct_sot_last_10_sot_Header,home_pct_sot_last_10_sot_Foot,home_pct_blocks_last_10_blocks_Header,home_pct_blocks_last_10_blocks_Foot,home_elo_rating,home_elo_opponent,home_elo_prob_win,home_elo_rating_split,home_elo_opponent_split,home_elo_prob_win_split,home_elo_rating_home_venue,home_elo_rating_away_venue,home_elo_diff_home_away,home_elo_opponent_home_venue,home_elo_opponent_away_venue,home_yellow_cards_elo_pre,home_yellow_cards_elo_opp_pre,home_yellow_cards_elo_prob,home_corners_elo_pre,home_corners_elo_opp_pre,home_corners_elo_prob,home_total_shots_elo_pre,home_total_shots_elo_opp_pre,home_total_shots_elo_prob,home_elo_rating_vs_league,home_elo_opponent_vs_league,home_elo_rating_split_vs_league,home_elo_opponent_split_vs_league,home_elo_rating_home_venue_vs_league,home_elo_rating_away_venue_vs_league,home_elo_opponent_home_venue_vs_league,home_elo_opponent_away_venue_vs_league,home_roll_5_sp_xg_for,home_roll_5_sp_goals_for,home_roll_5_sp_xg_against,home_roll_5_sp_goals_against,home_roll_5_pen_conversion_rate,home_roll_5_pen_save_luck,home_roll_10_sp_xg_for,home_roll_10_sp_goals_for,home_roll_10_sp_xg_against,home_roll_10_sp_goals_against,home_roll_10_pen_conversion_rate,home_roll_10_pen_save_luck,home_roll_20_sp_xg_for,home_roll_20_sp_goals_for,home_roll_20_sp_xg_against,home_roll_20_sp_goals_against,home_roll_20_pen_conversion_rate,home_roll_20_pen_save_luck,home_gk_avg_goals_prevented_last_5,home_gk_avg_save_pct_last_5,home_gk_avg_sweeper_actions_last_5,home_gk_avg_goals_prevented_last_10,home_gk_avg_save_pct_last_10,home_gk_avg_sweeper_actions_last_10,home_gk_avg_goals_prevented_last_20,home_gk_avg_save_pct_last_20,home_gk_avg_sweeper_actions_last_20,home_ewma_goals_for_5,home_ewma_goals_against_5,home_ewma_xg_for_5,home_ewma_xg_against_5,home_ewma_goals_for_10,home_ewma_goals_against_10,home_ewma_xg_for_10,home_ewma_xg_against_10,home_n_defenders,home_n_midfielders,home_n_forwards,home_opp_n_defenders,home_opp_n_midfielders,home_opp_n_forwards,home_tactics_is_back_three,home_tactics_is_lone_striker,home_tactics_midfield_diff,home_tactics_def_overload,home_tactics_changed_formation,home_tactics_instability_index_last_10,home_ref_team_win_pct_smoothed,home_ref_team_cards_vs_league,home_ref_team_fouls_vs_league,home_avg_minute_first_goal_last_20,home_pct_conceded_header_last_20,home_pct_conceded_penalty_last_20,home_pct_conceded_set_piece_last_20,home_pct_team_scores_first_goal_last_20,home_pct_team_receives_first_goal_last_20,home_pct_game_goal_before_30m_last_20,home_pct_team_clean_sheet_last_20,home_pct_team_btts_last_20,home_pct_team_game_over_1_5_goals_last_20,home_pct_team_game_over_2_5_goals_last_20,home_pct_team_scores_first_half_last_20,home_pct_team_scores_second_half_last_20,home_pct_team_over_2_5_cards_last_20,home_pct_team_over_4_5_cards_last_20,home_pct_team_over_6_5_cards_last_20,home_pct_team_over_9_corners_last_20,home_pct_team_over_11_corners_last_20,home_pct_team_over_13_corners_last_20,home_pct_team_over_3_5_sot_last_20,home_pct_team_over_5_5_sot_last_20,home_pct_team_over_7_5_sot_last_20,home_pct_team_over_9_5_sot_last_20,home_pct_team_over_11_5_sot_last_20,home_pct_team_games_over_5_5_sot_last_20,home_pct_team_games_over_7_5_sot_last_20,home_pct_team_games_over_9_5_sot_last_20,home_pct_team_games_over_11_5_sot_last_20,home_pct_team_shots_over_9_5_last_20,home_pct_team_shots_over_11_5_last_20,home_pct_team_shots_over_13_5_last_20,home_pct_team_shots_over_15_5_last_20,home_pct_team_shots_over_17_5_last_20,home_pct_team_shots_over_19_5_last_20,home_pct_team_games_shots_over_20_5_last_20,home_pct_team_games_shots_over_22_5_last_20,home_pct_team_games_shots_over_24_5_last_20,home_pct_team_games_shots_over_26_5_last_20,home_pct_team_games_shots_over_28_5_last_20,home_pct_team_games_shots_over_30_5_last_20,away_venue_id,away_referee_id,away_macro_rolling_goals,away_macro_rolling_fouls,away_macro_rolling_yellows,away_team_avg_goals_last_5,away_team_avg_xg_last_5,away_team_avg_buildup_last_5,away_team_avg_conceded_last_5,away_team_clean_sheet_pct_last_5,away_team_avg_xga_last_5,away_team_avg_ppda_last_5,away_team_avg_yellows_last_5,away_opponent_avg_yellows_last_5,away_team_avg_reds_last_5,away_opponent_avg_reds_last_5,away_team_avg_cards_per_foul_last_5,away_team_avg_fouls_committed_last_5,away_team_avg_fouls_drawn_last_5,away_team_avg_fouls_padj_last_5,away_team_avg_tackles_last_5,away_team_avg_tackle_fail_rate_last_5,away_opponent_avg_tackles_last_5,away_opponent_avg_tackles_succ_last_5,away_opponent_avg_tackle_succ_rate_last_5,away_team_avg_possession_last_5,away_opponent_avg_dribbles_last_5,away_team_avg_dribbles_last_5,away_team_avg_duels_last_5,away_team_avg_aerial_duels_last_5,away_team_avg_aerial_win_rate_last_5,away_team_avg_fouled_final_third_last_5,away_team_avg_foul_opp_final_third_last_5,away_team_avg_dispossessed_last_5,away_opponent_avg_dispossessed_last_5,away_team_avg_clearances_last_5,away_team_avg_recoveries_last_5,away_opponent_avg_touches_in_box_last_5,away_team_avg_touches_in_box_last_5,away_team_avg_sot_last_5,away_opponent_avg_sot_last_5,away_team_avg_shots_last_5,away_team_avg_shots_faced_last_5,away_team_avg_corners_last_5,away_team_avg_corners_against_last_5,away_opponent_avg_crosses_last_5,away_team_avg_crosses_last_5,away_team_avg_free_kicks_last_5,away_team_avg_offsides_last_5,away_opponent_avg_offsides_last_5,away_team_avg_goal_kicks_last_5,away_opponent_avg_goal_kicks_last_5,away_team_avg_goals_last_10,away_team_avg_xg_last_10,away_team_avg_buildup_last_10,away_team_avg_conceded_last_10,away_team_clean_sheet_pct_last_10,away_team_avg_xga_last_10,away_team_avg_ppda_last_10,away_team_avg_yellows_last_10,away_opponent_avg_yellows_last_10,away_team_avg_reds_last_10,away_opponent_avg_reds_last_10,away_team_avg_cards_per_foul_last_10,away_team_avg_fouls_committed_last_10,away_team_avg_fouls_drawn_last_10,away_team_avg_fouls_padj_last_10,away_team_avg_tackles_last_10,away_team_avg_tackle_fail_rate_last_10,away_opponent_avg_tackles_last_10,away_opponent_avg_tackles_succ_last_10,away_opponent_avg_tackle_succ_rate_last_10,away_team_avg_possession_last_10,away_opponent_avg_dribbles_last_10,away_team_avg_dribbles_last_10,away_team_avg_duels_last_10,away_team_avg_aerial_duels_last_10,away_team_avg_aerial_win_rate_last_10,away_team_avg_fouled_final_third_last_10,away_team_avg_foul_opp_final_third_last_10,away_team_avg_dispossessed_last_10,away_opponent_avg_dispossessed_last_10,away_team_avg_clearances_last_10,away_team_avg_recoveries_last_10,away_opponent_avg_touches_in_box_last_10,away_team_avg_touches_in_box_last_10,away_team_avg_sot_last_10,away_opponent_avg_sot_last_10,away_team_avg_shots_last_10,away_team_avg_shots_faced_last_10,away_team_avg_corners_last_10,away_team_avg_corners_against_last_10,away_opponent_avg_crosses_last_10,away_team_avg_crosses_last_10,away_team_avg_free_kicks_last_10,away_team_avg_offsides_last_10,away_opponent_avg_offsides_last_10,away_team_avg_goal_kicks_last_10,away_opponent_avg_goal_kicks_last_10,away_team_avg_goals_last_20,away_team_avg_xg_last_20,away_team_avg_buildup_last_20,away_team_avg_conceded_last_20,away_team_clean_sheet_pct_last_20,away_team_avg_xga_last_20,away_team_avg_ppda_last_20,away_team_avg_yellows_last_20,away_opponent_avg_yellows_last_20,away_team_avg_reds_last_20,away_opponent_avg_reds_last_20,away_team_avg_cards_per_foul_last_20,away_team_avg_fouls_committed_last_20,away_team_avg_fouls_drawn_last_20,away_team_avg_fouls_padj_last_20,away_team_avg_tackles_last_20,away_team_avg_tackle_fail_rate_last_20,away_opponent_avg_tackles_last_20,away_opponent_avg_tackles_succ_last_20,away_opponent_avg_tackle_succ_rate_last_20,away_team_avg_possession_last_20,away_opponent_avg_dribbles_last_20,away_team_avg_dribbles_last_20,away_team_avg_duels_last_20,away_team_avg_aerial_duels_last_20,away_team_avg_aerial_win_rate_last_20,away_team_avg_fouled_final_third_last_20,away_team_avg_foul_opp_final_third_last_20,away_team_avg_dispossessed_last_20,away_opponent_avg_dispossessed_last_20,away_team_avg_clearances_last_20,away_team_avg_recoveries_last_20,away_opponent_avg_touches_in_box_last_20,away_team_avg_touches_in_box_last_20,away_team_avg_sot_last_20,away_opponent_avg_sot_last_20,away_team_avg_shots_last_20,away_team_avg_shots_faced_last_20,away_team_avg_corners_last_20,away_team_avg_corners_against_last_20,away_opponent_avg_crosses_last_20,away_team_avg_crosses_last_20,away_team_avg_free_kicks_last_20,away_team_avg_offsides_last_20,away_opponent_avg_offsides_last_20,away_team_avg_goal_kicks_last_20,away_opponent_avg_goal_kicks_last_20,away_xi_avg_last_5_goals,away_xi_avg_last_5_xg,away_xi_avg_last_5_shots_taken,away_xi_avg_last_20_goals,away_xi_avg_last_20_xg,away_xi_avg_season_yellow_cards_per_90,away_xi_avg_season_red_cards_per_90,away_xi_avg_season_fouls_committed_per_90,away_xi_avg_season_goals_per_game,away_xi_avg_season_xg_per_game,away_xi_avg_finishing_overperformance_per_90,away_xi_avg_recent_match_fitness,away_starters_count,away_roll_5_line_xg_ATT,away_roll_5_line_xg_BENCH,away_roll_5_line_xg_DEF,away_roll_5_line_xg_MID,away_roll_5_line_goals_ATT,away_roll_5_line_goals_BENCH,away_roll_5_line_goals_DEF,away_roll_5_line_goals_MID,away_roll_5_line_sot_ATT,away_roll_5_line_sot_BENCH,away_roll_5_line_sot_DEF,away_roll_5_line_sot_MID,away_roll_5_line_tackles_ATT,away_roll_5_line_tackles_BENCH,away_roll_5_line_tackles_DEF,away_roll_5_line_tackles_MID,away_roll_5_line_fouls_ATT,away_roll_5_line_fouls_BENCH,away_roll_5_line_fouls_DEF,away_roll_5_line_fouls_MID,away_roll_5_line_market_val_ATT,away_roll_5_line_market_val_BENCH,away_roll_5_line_market_val_DEF,away_roll_5_line_market_val_MID,away_roll_5_team_match_shot_hhi,away_roll_5_team_match_top_shooter_shots,away_roll_5_team_squad_value_eur,away_team_last_20_goal_dependency_top2,away_schedule_days_rest,away_schedule_next_game_is_high_priority,away_schedule_next_game_is_diff_tournament,away_schedule_avg_opp_elo_vs_league_last_5,away_schedule_next_opp_elo_vs_league,away_schedule_is_trap_game,away_season_ppg,away_season_gd_per_game,away_global_form_points_last_5,away_pct_goals_last_5_goals_Mid_Left,away_pct_goals_last_5_goals_Close_Center,away_pct_goals_last_5_goals_Mid_Center,away_pct_goals_last_5_goals_Deep_Center,away_pct_goals_last_5_goals_Close_Left,away_pct_goals_last_5_goals_Mid_Right,away_pct_goals_last_5_goals_Deep_Right,away_pct_goals_last_5_goals_Deep_Left,away_pct_goals_last_5_goals_Close_Right,away_pct_sot_last_5_sot_Mid_Left,away_pct_sot_last_5_sot_Close_Center,away_pct_sot_last_5_sot_Mid_Center,away_pct_sot_last_5_sot_Deep_Center,away_pct_sot_last_5_sot_Close_Left,away_pct_sot_last_5_sot_Mid_Right,away_pct_sot_last_5_sot_Deep_Right,away_pct_sot_last_5_sot_Deep_Left,away_pct_sot_last_5_sot_Close_Right,away_pct_blocks_last_5_blocks_Mid_Left,away_pct_blocks_last_5_blocks_Close_Center,away_pct_blocks_last_5_blocks_Mid_Center,away_pct_blocks_last_5_blocks_Deep_Center,away_pct_blocks_last_5_blocks_Close_Left,away_pct_blocks_last_5_blocks_Mid_Right,away_pct_blocks_last_5_blocks_Deep_Right,away_pct_blocks_last_5_blocks_Deep_Left,away_pct_blocks_last_5_blocks_Close_Right,away_pct_goals_last_5_goals_Header,away_pct_goals_last_5_goals_Foot,away_pct_sot_last_5_sot_Header,away_pct_sot_last_5_sot_Foot,away_pct_blocks_last_5_blo

In [27]:
### Eliminar matches que fueron a OT
tms_match_stats = pd.read_parquet(DATA_PATH + 'team_match_stats.parquet')

# Inspect
# tms_match_stats['period'].value_counts()
# Filtering
matches_with_extra_time = (
    tms_match_stats.loc[
        (tms_match_stats["period"] == "ET1") &
        (tms_match_stats["possession_percentage"].notna()),
        "match_id"
    ]
    .unique()
)

DOUBLE_LEG_CROSS_TOURNAMENT = [
    "uefa-europa-league",
    "uefa-champions-league",
    "conference-league",
    "copa_de_italia",
    "copa-del-rey",
    "carabao-cup",
]


df_filtered = df[
    ~(
        df["match_id"].isin(matches_with_extra_time) &
        df["tournament"].isin(DOUBLE_LEG_CROSS_TOURNAMENT)
    )
]
print(f"The Number of matches eliminated on this filter is: {df.shape[0] - df_filtered.shape[0]}")

df_filtered.shape

The Number of matches eliminated on this filter is: 93

(14069, 1410)

,team_match_stat_id,match_id,team_id,is_home_team,period,formation,average_team_rating,total_team_market_value_eur,possession_percentage,big_chances,total_shots,saves,corners,fouls,passes_successful,passes_total,passes_percentage,tackles_successful,tackles_total,tackles_won_percentage,free_kicks,yellow_cards,red_cards,shots_on_target,hit_woodwork,shots_off_target,blocked_shots,shots_inside_box,shots_outside_box,big_chances_missed,fouled_final_third,offsides,accurate_passes_percentage,throw_ins,through_balls,final_third_entries,final_third_passes_successful,final_third_passes_total,final_third_passes_percentage,long_balls_successful,long_balls_total,long_balls_percentage,crosses_successful,crosses_total,crosses_percentage,duels_won_successful,duels_won_total,duels_won_percentage,dispossessed,ground_duels_successful,ground_duels_total,ground_duels_percentage,aerial_duels_successful,aerial_duels_total,aerial_duels_percentage,dribbles_successful,dribbles_total,dribbles_percentage,interceptions,clearances,goal_kicks,expected_goals,touches_in_penalty_area,passes_in_final_third,recoveries,errors_lead_to_shot,goals_prevented,big_saves,errors_lead_to_goal,penalty_saves,big_chances_scored,created_at
0,91253,9541708,2673,True,ALL,4-3-3,6.69,516852000.0,0.49,3,8,2,5,13,364.0,456.0,0.7982,14.0,27.0,0.5185,12,2,0,5,0,3,0,5,3,3,4,4,0.7982,19,2,49,NaN,NaN,NaN,21.0,41.0,0.5122,1.0,14.0,0.0714,53,103,0.51,4,47.0,85.0,0.5529,6.0,18.0,0.3333,8.0,18.0,0.4444,12,10,5,NaN,0,0,0,0,NaN,0,0,0,0,2025-09-02 21:33:45.103854
1,91255,9541708,2673,True,1ST,None,NaN,NaN,0.49,2,4,0,2,0,184.0,229.0,0.8035,3.0,9.0,0.3333,6,2,0,3,0,1,0,3,1,2,1,2,0.8035,12,1,21,NaN,NaN,NaN,13.0,21.0,0.6190,0.0,6.0,0.0000,24,47,0.51,2,19.0,39.0,0.4872,5.0,8.0,0.6250,4.0,7.0,0.5714,4,7,3,NaN,0,0,0,0,NaN,0,0,0,0,2025-09-02 21:33:45.103854
2,91256,9541708,2672,False,1ST,None,NaN,NaN,0.51,4,10,3,4,0,190.0,230.0,0.8261,0.0,5.0,0.0000,10,1,0,2,0,5,3,10,0,3,2,0,0.8261,9,1,23,NaN,NaN,NaN,24.0,39.0,0.6154,6.0,12.0,0.5000,23,47,0.49,4,20.0,39.0,0.5128,3.0,8.0,0.3750,6.0,11.0,0.5455,7,7,1,NaN,0,0,0,0,NaN,0,0,0,1,2025-09-02 21:33:45.103854
3,91257,9541708,2673,True,2ND,None,NaN,NaN,0.49,1,4,2,3,0,180.0,227.0,0.7930,11.0,18.0,0.6111,6,0,0,2,0,2,0,2,2,1,3,2,0.7930,7,1,28,NaN,NaN,NaN,8.0,20.0,0.4000,1.0,8.0,0.1250,29,56,0.52,2,28.0,46.0,0.6087,1.0,10.0,0.1000,4.0,11.0,0.3636,8,3,2,NaN,0,0,0,0,NaN,0,0,0,0,2025-09-02 21:33:45.103854
4,91258,9541708,2672,False,2ND,None,NaN,NaN,0.51,2,7,1,2,0,191.0,242.0,0.7893,6.0,9.0,0.6667,3,2,0,4,0,3,0,3,4,0,1,0,0.7893,11,0,20,NaN,NaN,NaN,15.0,28.0,0.5357,0.0,4.0,0.0000,27,56,0.48,11,18.0,46.0,0.3913,9.0,10.0,0.9000,7.0,14.0,0.5000,4,12,5,NaN,0,0,0,0,NaN,0,0,0,2,2025-09-02 21:33:45.103854